gitops-runtime:
  global:
    codefresh:
      accountId: 6602c35f9b7fdd33f1324389
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
